### ISSUE TITLE
take inventory of and update any commands to work with glimmer

### ISSUE THREAD

**Issue by koryteg** [koryteg/glimmer-rails#5]
the `ember-cli-rails` gem is currently a bunch of commands and integrations into the build pipeline that make it easy to run and point to an ember build. I think we can update the tests and app code that get generated to act like a glimmer app and start changing the gem to follow suit.

**Comment by mswanson** [comment]
closing this since https://github.com/koryteg/glimmer-rails/issues/6 covers it.
